_target_: src.models.centernet_module.CenterNet

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0004
  weight_decay: 0.1

scheduler:
  _target_: torch.optim.lr_scheduler.StepLR
  _partial_: true
  step_size: 30
  gamma: 0.1

gaussian_iou: 0.7

net:
  num_classes: ???